spring.config.activate.on-profile: dev
spring:
  application:
    name: app-dev
  datasource:
    url: jdbc:postgresql://192.168.99.104:5432/postgres
    username: postgres
    password: postgres
  liquibase:
    default-schema: app_dev
  ai:
    openai:
      embedding:
        enabled: false
server:
  port: 8080
